In [1]:
from itertools import product
import numpy as np
import pandas as pd
from model_settings import vanilla_pricer
vanilla = vanilla_pricer.vanilla_pricer()
s = 100
K = np.linspace(s*0.5,s*1.5,5).astype(int).astype(float).tolist()
T = np.arange(1,365+1,1)
r = [0.04]
vols = np.linspace(0.1,0.9,5)

features = pd.DataFrame(
    product(
        [s],
        K,
        T,
        r,
        vols,
        ['call','put']
    ),
    columns = ['spot_price','strike_price','days_to_maturity','risk_free_rate','volatility','w']
)
features['price'] = vanilla.df_numpy_black_scholes(features)
features

vanilla option pricer initialized
Actual365Fixed

,spot_price,strike_price,days_to_maturity,risk_free_rate,volatility,w,price
0,100,50.0,1,0.04,0.1,call,50.005479
1,100,50.0,1,0.04,0.1,put,0.000000
2,100,50.0,1,0.04,0.3,call,50.005479
3,100,50.0,1,0.04,0.3,put,0.000000
4,100,50.0,1,0.04,0.5,call,50.005479
...,...,...,...,...,...,...,...
18245,100,150.0,365,0.04,0.5,put,52.110227
18246,100,150.0,365,0.04,0.7,call,15.558184
18247,100,150.0,365,0.04,0.7,put,59.676600
18248,100,150.0,365,0.04,0.9,call,23.507730
18249,100,150.0,365,0.04,0.9,put,67.626146